In [23]:
import pandas as pd
import numpy as np
import math

In [24]:
students = pd.read_csv("students")

In [25]:
students

   Unnamed: 0  student_id   name    major
0           0         101  Amina     Math
1           1         102  Bilal  Biology
2           2         103   Chen     Math
3           3         104  Dalia  Physics
4           4         105    Eze     Math

In [26]:
grades = pd.read_csv("grades")

In [27]:
grades

   Unnamed: 0  student_id   course  grade
0           0         101  MATH014     92
1           1         101  MATH156     88
2           2         102   BIO101     75
3           3         103  MATH014     84
4           4         104  PHYS201     68
5           5         106  MATH014     79

In [28]:
students = students.drop("Unnamed: 0", axis=1)

In [29]:
grades = grades.drop("Unnamed: 0", axis=1)

In [30]:
students

   student_id   name    major
0         101  Amina     Math
1         102  Bilal  Biology
2         103   Chen     Math
3         104  Dalia  Physics
4         105    Eze     Math

In [31]:
grades

   student_id   course  grade
0         101  MATH014     92
1         101  MATH156     88
2         102   BIO101     75
3         103  MATH014     84
4         104  PHYS201     68
5         106  MATH014     79

## Merge

In [32]:
# how merge works
# combines based on the specificied column. For IDs that exist on both sides, it creates a row of combined data. For IDs that don't exist on both sides
# the row will be removed (if how is specified as "inner"). If the ID is repeated on one side more than the other, a separate row is created for each 
# instance of the ID on the most repeated side.

In [33]:
stugrad1 = students.merge(grades, on="student_id", how="inner")

In [34]:
stugrad1

   student_id   name    major   course  grade
0         101  Amina     Math  MATH014     92
1         101  Amina     Math  MATH156     88
2         102  Bilal  Biology   BIO101     75
3         103   Chen     Math  MATH014     84
4         104  Dalia  Physics  PHYS201     68

In [ ]:
# if how is defined as "outer", then rows not included on both sections will have NaN on areas not specified by one dataframe

In [35]:
students.merge(grades, on="student_id", how="outer")

   student_id   name    major   course  grade
0         101  Amina     Math  MATH014   92.0
1         101  Amina     Math  MATH156   88.0
2         102  Bilal  Biology   BIO101   75.0
3         103   Chen     Math  MATH014   84.0
4         104  Dalia  Physics  PHYS201   68.0
5         105    Eze     Math      NaN    NaN
6         106    NaN      NaN  MATH014   79.0

In [ ]:
# If how is defined as "left", it will put in everything on the 'left' (first mentioned) table, and put corresponding info on the right.
# If how is defined as "right", the opposite will take place.

In [36]:
students.merge(grades, on="student_id", how="left")

   student_id   name    major   course  grade
0         101  Amina     Math  MATH014   92.0
1         101  Amina     Math  MATH156   88.0
2         102  Bilal  Biology   BIO101   75.0
3         103   Chen     Math  MATH014   84.0
4         104  Dalia  Physics  PHYS201   68.0
5         105    Eze     Math      NaN    NaN

In [37]:
students.merge(grades, on="student_id", how="right")

   student_id   name    major   course  grade
0         101  Amina     Math  MATH014     92
1         101  Amina     Math  MATH156     88
2         102  Bilal  Biology   BIO101     75
3         103   Chen     Math  MATH014     84
4         104  Dalia  Physics  PHYS201     68
5         106    NaN      NaN  MATH014     79

## Join

In [42]:
s_id = students.set_index("student_id")
g_id = grades.set_index('student_id')

# no need to specify 'on' because it is always joining on the previously specified index (which was "student_id")

s_id.join(g_id)

             name    major   course  grade
student_id
101         Amina     Math  MATH014   92.0
101         Amina     Math  MATH156   88.0
102         Bilal  Biology   BIO101   75.0
103          Chen     Math  MATH014   84.0
104         Dalia  Physics  PHYS201   68.0
105           Eze     Math      NaN    NaN

In [43]:
s_id

             name    major
student_id
101         Amina     Math
102         Bilal  Biology
103          Chen     Math
104         Dalia  Physics
105           Eze     Math

In [46]:
g_id.join(s_id)

             course  grade   name    major
student_id
101         MATH014     92  Amina     Math
101         MATH156     88  Amina     Math
102          BIO101     75  Bilal  Biology
103         MATH014     84   Chen     Math
104         PHYS201     68  Dalia  Physics
106         MATH014     79    NaN      NaN

## concat

In [47]:
fall_roster = pd.DataFrame({
    "student_id": [101, 102], "name": ["Amina", "Bilal"], "credits": [15, 12]})
spring_roster = pd.DataFrame({
    "student_id": [103, 104], "name": ["Chen", "Dalia"], "credits": [16, 14]})

print("fall_roster");   print(fall_roster)
print("\nspring_roster"); print(spring_roster)

fall_roster
   student_id   name  credits
0         101  Amina       15
1         102  Bilal       12

spring_roster
   student_id   name  credits
0         103   Chen       16
1         104  Dalia       14

In [48]:
fall_roster

   student_id   name  credits
0         101  Amina       15
1         102  Bilal       12

In [54]:
stacked = pd.concat([fall_roster, spring_roster])
stacked

   student_id   name  credits
0         101  Amina       15
1         102  Bilal       12
0         103   Chen       16
1         104  Dalia       14

In [53]:
long = pd.concat([fall_roster, spring_roster], axis=1)
long

   student_id   name  credits  student_id   name  credits
0         101  Amina       15         103   Chen       16
1         102  Bilal       12         104  Dalia       14

In [ ]:
# homework - write a paragraph about something nice about yourself and have a nice professional headshot of yourself. Go to google, type: "html5up 
# template". Also, download vs code.