## Installing and Importing NumPy

In [1]:
# definition: NumPy stands for Numerical Python (any math you do on here either directly or indirectly uses numpy)

In [2]:
# to use NumPy, you first need to import it. By convention, we use: import numpy as np
# SymPy is a library of NumPy that does professional looking prints

In [48]:
import numpy as np
import sympy as sy
import random

In [6]:
# Difference between numpy object and a list

In [8]:
n_list = [5,12,16,31]

In [10]:
n_list*2
# Won't double the numbers, but just repeats them again

[5, 12, 16, 31, 5, 12, 16, 31]

In [11]:
n_list**(0.5)

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'float'

In [12]:
# fun facts: numpy is lighter on ur computer than regular math

In [13]:
# numpy array
array_1 = np.array([5,12,16,31])

In [14]:
array_1*2

array([10, 24, 32, 62])

In [15]:
array_1**(0.5)

array([2.23606798, 3.46410162, 4.        , 5.56776436])

In [17]:
# 2D arrays
mat_1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [18]:
mat_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
mat_2 = sy.Matrix([[1,2,3],[4,5,6],[7,8,9]])

In [20]:
mat_2

Matrix([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])

In [21]:
# SymPy just makes it look pretty yk

In [23]:
# Zero matrix
Z = np.zeros((3,3))

In [24]:
Z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
# Ones matrix
O_1 = np.ones((3,3))

In [30]:
O_1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [31]:
# Identity Matrix
I_1 = np.eye(5)

In [32]:
I_1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
# Zeros martix using sympy
Z_2 = sy.Matrix(np.zeros((2,2)))

In [35]:
Z_2

Matrix([
[0.0, 0.0],
[0.0, 0.0]])

In [36]:
sy.Matrix(np.zeros((5,5)))

Matrix([
[0.0, 0.0, 0.0, 0.0, 0.0],
[0.0, 0.0, 0.0, 0.0, 0.0],
[0.0, 0.0, 0.0, 0.0, 0.0],
[0.0, 0.0, 0.0, 0.0, 0.0],
[0.0, 0.0, 0.0, 0.0, 0.0]])

In [37]:
sy.Matrix(np.eye(5))

Matrix([
[1.0, 0.0, 0.0, 0.0, 0.0],
[0.0, 1.0, 0.0, 0.0, 0.0],
[0.0, 0.0, 1.0, 0.0, 0.0],
[0.0, 0.0, 0.0, 1.0, 0.0],
[0.0, 0.0, 0.0, 0.0, 1.0]])

In [39]:
sy.Matrix(np.ones((3,2)))

Matrix([
[1.0, 1.0],
[1.0, 1.0],
[1.0, 1.0]])

In [40]:
I_2 = sy.eye(2)

In [41]:
I_2

Matrix([
[1, 0],
[0, 1]])

In [42]:
O_2 = sy.ones(2,3)

In [43]:
O_2

Matrix([
[1, 1, 1],
[1, 1, 1]])

## PANDAS

In [45]:
# PANDAS is our main library that we'll use for the semester. Allows you to manipulate files and other such things

In [46]:
# import pandas as pd (to be able to use pandas)

In [35]:
import pandas as pd
import numpy as np
import random

In [ ]:
# df = data frame (DO NOT RUN THIS LINE)
df = pd.read_csv("[name of csv file here]")
# the file you are reading must be in the same folder as this file OR you must make a path to it as shown below
df = pd.read_csv("~/[folder name]/[folder name]/[name of csv file here]")

In [50]:
df = pd.DataFrame(np.random.randn(3,4))

In [51]:
df

          0         1         2         3
0  0.335053  1.661550 -1.091935 -0.046935
1  0.025063 -0.482668 -0.113566  0.316173
2 -0.030188 -1.318933 -0.682585  0.611851

In [54]:
df = pd.DataFrame(np.random.randn(3,3),index = "A B C".split(" "), columns = "x%y%z".split("%"))

In [56]:
df

          x         y         z
A  0.161397  0.762635 -0.337453
B -0.282590  0.691525 -0.074251
C  0.710836  0.331506 -0.661918

### LAMBDA EXPRESSIONS

In [3]:
students = [{"name":"Maya", "GPA":3.9, "Major":"Math"},
            {"name":"Amara", "GPA":3.75, "Major":"Economics"},
            {"name":"Kolby", "GPA":3.99, "Major":"Math"},
            {"name":"Ava", "GPA":4.0, "Major":"Data Science"},
            {"name":"Gaby", "GPA":3.95, "Major":"AI"},
            ]

In [4]:
students

[{'name': 'Maya', 'GPA': 3.9, 'Major': 'Math'},
 {'name': 'Amara', 'GPA': 3.75, 'Major': 'Economics'},
 {'name': 'Kolby', 'GPA': 3.99, 'Major': 'Math'},
 {'name': 'Ava', 'GPA': 4.0, 'Major': 'Data Science'},
 {'name': 'Gaby', 'GPA': 3.95, 'Major': 'AI'}]

In [10]:
ranked = sorted(students,
                key=lambda s: (-s["GPA"], s["Major"], s["name"]))

In [11]:
for s in ranked:
    print(f'{s["Major"]:<20}{s["GPA"]}{s["name"]:>10}')

Data Science        4.0       Ava
Math                3.99     Kolby
AI                  3.95      Gaby
Math                3.9      Maya
Economics           3.75     Amara

In [12]:
def multiply(a,b):
    return a*b

In [14]:
multiply(9,30)

270

In [16]:
ml = lambda a,b: a*b

In [17]:
ml(5,8)

40

In [18]:
def sqrn(numb):
    return numb**2

In [19]:
sqrn(36)

1296

In [20]:
sqrnew = lambda numb: numb**2

In [21]:
sqrnew(42)

1764

### Back to PANDAS

In [66]:
number_rows, number_columns = 1000, 100

In [78]:
rows_name = [f"Row{i}" for i in range(number_rows)]
columns_name = [f"Column{j}" for j in range(number_columns)]

In [79]:
rows_name

['Row0',
 'Row1',
 'Row2',
 'Row3',
 'Row4',
 'Row5',
 'Row6',
 'Row7',
 'Row8',
 'Row9',
 'Row10',
 'Row11',
 'Row12',
 'Row13',
 'Row14',
 'Row15',
 'Row16',
 'Row17',
 'Row18',
 'Row19',
 'Row20',
 'Row21',
 'Row22',
 'Row23',
 'Row24',
 'Row25',
 'Row26',
 'Row27',
 'Row28',
 'Row29',
 'Row30',
 'Row31',
 'Row32',
 'Row33',
 'Row34',
 'Row35',
 'Row36',
 'Row37',
 'Row38',
 'Row39',
 'Row40',
 'Row41',
 'Row42',
 'Row43',
 'Row44',
 'Row45',
 'Row46',
 'Row47',
 'Row48',
 'Row49',
 'Row50',
 'Row51',
 'Row52',
 'Row53',
 'Row54',
 'Row55',
 'Row56',
 'Row57',
 'Row58',
 'Row59',
 'Row60',
 'Row61',
 'Row62',
 'Row63',
 'Row64',
 'Row65',
 'Row66',
 'Row67',
 'Row68',
 'Row69',
 'Row70',
 'Row71',
 'Row72',
 'Row73',
 'Row74',
 'Row75',
 'Row76',
 'Row77',
 'Row78',
 'Row79',
 'Row80',
 'Row81',
 'Row82',
 'Row83',
 'Row84',
 'Row85',
 'Row86',
 'Row87',
 'Row88',
 'Row89',
 'Row90',
 'Row91',
 'Row92',
 'Row93',
 'Row94',
 'Row95',
 'Row96',
 'Row97',
 'Row98',
 'Row99',
 'Row100',
 'Row101',
 'Row102',
 'Row103',
 'Row104',
 'Row105',
 'Row106',
 'Row107',
 'Row108',
 'Row109',
 'Row110',
 'Row111',
 'Row112',
 'Row113',
 'Row114',
 'Row115',
 'Row116',
 'Row117',
 'Row118',
 'Row119',
 'Row120',
 'Row121',
 'Row122',
 'Row123',
 'Row124',
 'Row125',
 'Row126',
 'Row127',
 'Row128',
 'Row129',
 'Row130',
 'Row131',
 'Row132',
 'Row133',
 'Row134',
 'Row135',
 'Row136',
 'Row137',
 'Row138',
 'Row139',
 'Row140',
 'Row141',
 'Row142',
 'Row143',
 'Row144',
 'Row145',
 'Row146',
 'Row147',
 'Row148',
 'Row149',
 'Row150',
 'Row151',
 'Row152',
 'Row153',
 'Row154',
 'Row155',
 'Row156',
 'Row157',
 'Row158',
 'Row159',
 'Row160',
 'Row161',
 'Row162',
 'Row163',
 'Row164',
 'Row165',
 'Row166',
 'Row167',
 'Row168',
 'Row169',
 'Row170',
 'Row171',
 'Row172',
 'Row173',
 'Row174',
 'Row175',
 'Row176',
 'Row177',
 'Row178',
 'Row179',
 'Row180',
 'Row181',
 'Row182',
 'Row183',
 'Row184',
 'Row185',
 'Row186',
 'Row187',
 'Row188',
 'Row189',
 'Row190',
 'Row191',
 'Row192',
 'Row193',
 'Row194',
 'Row195',
 'Row196',
 'Row197',
 'Row198',
 'Row199',
 'Row200',
 'Row201',
 'Row202',
 'Row203',
 'Row204',
 'Row205',
 'Row206',
 'Row207',
 'Row208',
 'Row209',
 'Row210',
 'Row211',
 'Row212',
 'Row213',
 'Row214',
 'Row215',
 'Row216',
 'Row217',
 'Row218',
 'Row219',
 'Row220',
 'Row221',
 'Row222',
 'Row223',
 'Row224',
 'Row225',
 'Row226',
 'Row227',
 'Row228',
 'Row229',
 'Row230',
 'Row231',
 'Row232',
 'Row233',
 'Row234',
 'Row235',
 'Row236',
 'Row237',
 'Row238',
 'Row239',
 'Row240',
 'Row241',
 'Row242',
 'Row243',
 'Row244',
 'Row245',
 'Row246',
 'Row247',
 'Row248',
 'Row249',
 'Row250',
 'Row251',
 'Row252',
 'Row253',
 'Row254',
 'Row255',
 'Row256',
 'Row257',
 'Row258',
 'Row259',
 'Row260',
 'Row261',
 'Row262',
 'Row263',
 'Row264',
 'Row265',
 'Row266',
 'Row267',
 'Row268',
 'Row269',
 'Row270',
 'Row271',
 'Row272',
 'Row273',
 'Row274',
 'Row275',
 'Row276',
 'Row277',
 'Row278',
 'Row279',
 'Row280',
 'Row281',
 'Row282',
 'Row283',
 'Row284',
 'Row285',
 'Row286',
 'Row287',
 'Row288',
 'Row289',
 'Row290',
 'Row291',
 'Row292',
 'Row293',
 'Row294',
 'Row295',
 'Row296',
 'Row297',
 'Row298',
 'Row299',
 'Row300',
 'Row301',
 'Row302',
 'Row303',
 'Row304',
 'Row305',
 'Row306',
 'Row307',
 'Row308',
 'Row309',
 'Row310',
 'Row311',
 'Row312',
 'Row313',
 'Row314',
 'Row315',
 'Row316',
 'Row317',
 'Row318',
 'Row319',
 'Row320',
 'Row321',
 'Row322',
 'Row323',
 'Row324',
 'Row325',
 'Row326',
 'Row327',
 'Row328',
 'Row329',
 'Row330',
 'Row331',
 'Row332',
 'Row333',
 'Row334',
 'Row335',
 'Row336',
 'Row337',
 'Row338',
 'Row339',
 'Row340',
 'Row341',
 'Row342',
 'Row343',
 'Row344',
 'Row345',
 'Row346',
 'Row347',
 'Row348',
 'Row349',
 'Row350',
 'Row351',
 'Row352',
 'Row353',
 'Row354',
 'Row355',
 'Row356',
 'Row357',
 'Row358',
 'Row359',
 'Row360',
 'Row361',
 'Row362',
 'Row363',
 'Row364',
 'Row365',
 'Row366',
 'Row367',
 'Row368',
 'Row369',
 'Row370',
 'Row371',
 'Row372',
 'Row373',
 'Row374',
 'Row375',
 'Row376',
 'Row377',
 'Row378',
 'Row379',
 'Row380',
 'Row381',
 'Row382',
 'Row383',
 'Row384',
 'Row385',
 'Row386',
 'Row387',
 'Row388',
 'Row389',
 'Row390',
 'Row391',
 'Row392',
 'Row393',
 'Row394',
 'Row395',
 'Row396',
 'Row397',
 'Row398',
 'Row399',
 'Row400',
 'Row401',
 'Row402',
 'Row403',
 'Row404',
 'Row405',
 'Row406',
 'Row407',
 'Row408',
 'Row409',
 'Row410',
 'Row411',
 'Row412',
 'Row413',
 'Row414',
 'Row415',
 'Row416',
 'Row417',
 'Row418',
 'Row419',
 'Row420',
 'Row421',
 'Row422',
 'Row423',
 'Row424',
 'Row425',
 'Row426',
 'Row427',
 'Row428',
 'Row429',
 'Row430',
 'Row431',
 'Row432',
 'Row433',
 'Row434',
 'Row435',
 'Row436',
 'Row437',
 'Row438',
 'Row439',
 'Row440',
 'Row441',
 'Row442',
 'Row443',
 'Row444',
 'Row445',
 'Row446',
 'Row447',
 'Row448',
 'Row449',
 'Row450',
 'Row451',
 'Row452',
 'Row453',
 'Row454',
 'Row455',
 'Row456',
 'Row457',
 'Row458',
 'Row459',
 'Row460',
 'Row461',
 'Row462',
 'Row463',
 'Row464',
 'Row465',
 'Row466',
 'Row467',
 'Row468',
 'Row469',
 'Row470',
 'Row471',
 'Row472',
 'Row473',
 'Row474',
 'Row475',
 'Row476',
 'Row477',
 'Row478',
 'Row479',
 'Row480',
 'Row481',
 'Row482',
 'Row483',
 'Row484',
 'Row485',
 'Row486',
 'Row487',
 'Row488',
 'Row489',
 'Row490',
 'Row491',
 'Row492',
 'Row493',
 'Row494',
 'Row495',
 'Row496',
 'Row497',
 'Row498',
 'Row499',
 'Row500',
 'Row501',
 'Row502',
 'Row503',
 'Row504',
 'Row505',
 'Row506',
 'Row507',
 'Row508',
 'Row509',
 'Row510',
 'Row511',
 'Row512',
 'Row513',
 'Row514',
 'Row515',
 'Row516',
 'Row517',
 'Row518',
 'Row519',
 'Row520',
 'Row521',
 'Row522',
 'Row523',
 'Row524',
 'Row525',
 'Row526',
 'Row527',
 'Row528',
 'Row529',
 'Row530',
 'Row531',
 'Row532',
 'Row533',
 'Row534',
 'Row535',
 'Row536',
 'Row537',
 'Row538',
 'Row539',
 'Row540',
 'Row541',
 'Row542',
 'Row543',
 'Row544',
 'Row545',
 'Row546',
 'Row547',
 'Row548',
 'Row549',
 'Row550',
 'Row551',
 'Row552',
 'Row553',
 'Row554',
 'Row555',
 'Row556',
 'Row557',
 'Row558',
 'Row559',
 'Row560',
 'Row561',
 'Row562',
 'Row563',
 'Row564',
 'Row565',
 'Row566',
 'Row567',
 'Row568',
 'Row569',
 'Row570',
 'Row571',
 'Row572',
 'Row573',
 'Row574',
 'Row575',
 'Row576',
 'Row577',
 'Row578',
 'Row579',
 'Row580',
 'Row581',
 'Row582',
 'Row583',
 'Row584',
 'Row585',
 'Row586',
 'Row587',
 'Row588',
 'Row589',
 'Row590',
 'Row591',
 'Row592',
 'Row593',
 'Row594',
 'Row595',
 'Row596',
 'Row597',
 'Row598',
 'Row599',
 'Row600',
 'Row601',
 'Row602',
 'Row603',
 'Row604',
 'Row605',
 'Row606',
 'Row607',
 'Row608',
 'Row609',
 'Row610',
 'Row611',
 'Row612',
 'Row613',
 'Row614',
 'Row615',
 'Row616',
 'Row617',
 'Row618',
 'Row619',
 'Row620',
 'Row621',
 'Row622',
 'Row623',
 'Row624',
 'Row625',
 'Row626',
 'Row627',
 'Row628',
 'Row629',
 'Row630',
 'Row631',
 'Row632',
 'Row633',
 'Row634',
 'Row635',
 'Row636',
 'Row637',
 'Row638',
 'Row639',
 'Row640',
 'Row641',
 'Row642',
 'Row643',
 'Row644',
 'Row645',
 'Row646',
 'Row647',
 'Row648',
 'Row649',
 'Row650',
 'Row651',
 'Row652',
 'Row653',
 'Row654',
 'Row655',
 'Row656',
 'Row657',
 'Row658',
 'Row659',
 'Row660',
 'Row661',
 'Row662',
 'Row663',
 'Row664',
 'Row665',
 'Row666',
 'Row667',
 'Row668',
 'Row669',
 'Row670',
 'Row671',
 'Row672',
 'Row673',
 'Row674',
 'Row675',
 'Row676',
 'Row677',
 'Row678',
 'Row679',
 'Row680',
 'Row681',
 'Row682',
 'Row683',
 'Row684',
 'Row685',
 'Row686',
 'Row687',
 'Row688',
 'Row689',
 'Row690',
 'Row691',
 'Row692',
 'Row693',
 'Row694',
 'Row695',
 'Row696',
 'Row697',
 'Row698',
 'Row699',
 'Row700',
 'Row701',
 'Row702',
 'Row703',
 'Row704',
 'Row705',
 'Row706',
 'Row707',
 'Row708',
 'Row709',
 'Row710',
 'Row711',
 'Row712',
 'Row713',
 'Row714',
 'Row715',
 'Row716',
 'Row717',
 'Row718',
 'Row719',
 'Row720',
 'Row721',
 'Row722',
 'Row723',
 'Row724',
 'Row725',
 'Row726',
 'Row727',
 'Row728',
 'Row729',
 'Row730',
 'Row731',
 'Row732',
 'Row733',
 'Row734',
 'Row735',
 'Row736',
 'Row737',
 'Row738',
 'Row739',
 'Row740',
 'Row741',
 'Row742',
 'Row743',
 'Row744',
 'Row745',
 'Row746',
 'Row747',
 'Row748',
 'Row749',
 'Row750',
 'Row751',
 'Row752',
 'Row753',
 'Row754',
 'Row755',
 'Row756',
 'Row757',
 'Row758',
 'Row759',
 'Row760',
 'Row761',
 'Row762',
 'Row763',
 'Row764',
 'Row765',
 'Row766',
 'Row767',
 'Row768',
 'Row769',
 'Row770',
 'Row771',
 'Row772',
 'Row773',
 'Row774',
 'Row775',
 'Row776',
 'Row777',
 'Row778',
 'Row779',
 'Row780',
 'Row781',
 'Row782',
 'Row783',
 'Row784',
 'Row785',
 'Row786',
 'Row787',
 'Row788',
 'Row789',
 'Row790',
 'Row791',
 'Row792',
 'Row793',
 'Row794',
 'Row795',
 'Row796',
 'Row797',
 'Row798',
 'Row799',
 'Row800',
 'Row801',
 'Row802',
 'Row803',
 'Row804',
 'Row805',
 'Row806',
 'Row807',
 'Row808',
 'Row809',
 'Row810',
 'Row811',
 'Row812',
 'Row813',
 'Row814',
 'Row815',
 'Row816',
 'Row817',
 'Row818',
 'Row819',
 'Row820',
 'Row821',
 'Row822',
 'Row823',
 'Row824',
 'Row825',
 'Row826',
 'Row827',
 'Row828',
 'Row829',
 'Row830',
 'Row831',
 'Row832',
 'Row833',
 'Row834',
 'Row835',
 'Row836',
 'Row837',
 'Row838',
 'Row839',
 'Row840',
 'Row841',
 'Row842',
 'Row843',
 'Row844',
 'Row845',
 'Row846',
 'Row847',
 'Row848',
 'Row849',
 'Row850',
 'Row851',
 'Row852',
 'Row853',
 'Row854',
 'Row855',
 'Row856',
 'Row857',
 'Row858',
 'Row859',
 'Row860',
 'Row861',
 'Row862',
 'Row863',
 'Row864',
 'Row865',
 'Row866',
 'Row867',
 'Row868',
 'Row869',
 'Row870',
 'Row871',
 'Row872',
 'Row873',
 'Row874',
 'Row875',
 'Row876',
 'Row877',
 'Row878',
 'Row879',
 'Row880',
 'Row881',
 'Row882',
 'Row883',
 'Row884',
 'Row885',
 'Row886',
 'Row887',
 'Row888',
 'Row889',
 'Row890',
 'Row891',
 'Row892',
 'Row893',
 'Row894',
 'Row895',
 'Row896',
 'Row897',
 'Row898',
 'Row899',
 'Row900',
 'Row901',
 'Row902',
 'Row903',
 'Row904',
 'Row905',
 'Row906',
 'Row907',
 'Row908',
 'Row909',
 'Row910',
 'Row911',
 'Row912',
 'Row913',
 'Row914',
 'Row915',
 'Row916',
 'Row917',
 'Row918',
 'Row919',
 'Row920',
 'Row921',
 'Row922',
 'Row923',
 'Row924',
 'Row925',
 'Row926',
 'Row927',
 'Row928',
 'Row929',
 'Row930',
 'Row931',
 'Row932',
 'Row933',
 'Row934',
 'Row935',
 'Row936',
 'Row937',
 'Row938',
 'Row939',
 'Row940',
 'Row941',
 'Row942',
 'Row943',
 'Row944',
 'Row945',
 'Row946',
 'Row947',
 'Row948',
 'Row949',
 'Row950',
 'Row951',
 'Row952',
 'Row953',
 'Row954',
 'Row955',
 'Row956',
 'Row957',
 'Row958',
 'Row959',
 'Row960',
 'Row961',
 'Row962',
 'Row963',
 'Row964',
 'Row965',
 'Row966',
 'Row967',
 'Row968',
 'Row969',
 'Row970',
 'Row971',
 'Row972',
 'Row973',
 'Row974',
 'Row975',
 'Row976',
 'Row977',
 'Row978',
 'Row979',
 'Row980',
 'Row981',
 'Row982',
 'Row983',
 'Row984',
 'Row985',
 'Row986',
 'Row987',
 'Row988',
 'Row989',
 'Row990',
 'Row991',
 'Row992',
 'Row993',
 'Row994',
 'Row995',
 'Row996',
 'Row997',
 'Row998',
 'Row999']

In [80]:
columns_name

['Column0',
 'Column1',
 'Column2',
 'Column3',
 'Column4',
 'Column5',
 'Column6',
 'Column7',
 'Column8',
 'Column9',
 'Column10',
 'Column11',
 'Column12',
 'Column13',
 'Column14',
 'Column15',
 'Column16',
 'Column17',
 'Column18',
 'Column19',
 'Column20',
 'Column21',
 'Column22',
 'Column23',
 'Column24',
 'Column25',
 'Column26',
 'Column27',
 'Column28',
 'Column29',
 'Column30',
 'Column31',
 'Column32',
 'Column33',
 'Column34',
 'Column35',
 'Column36',
 'Column37',
 'Column38',
 'Column39',
 'Column40',
 'Column41',
 'Column42',
 'Column43',
 'Column44',
 'Column45',
 'Column46',
 'Column47',
 'Column48',
 'Column49',
 'Column50',
 'Column51',
 'Column52',
 'Column53',
 'Column54',
 'Column55',
 'Column56',
 'Column57',
 'Column58',
 'Column59',
 'Column60',
 'Column61',
 'Column62',
 'Column63',
 'Column64',
 'Column65',
 'Column66',
 'Column67',
 'Column68',
 'Column69',
 'Column70',
 'Column71',
 'Column72',
 'Column73',
 'Column74',
 'Column75',
 'Column76',
 'Column77',
 'Column78',
 'Column79',
 'Column80',
 'Column81',
 'Column82',
 'Column83',
 'Column84',
 'Column85',
 'Column86',
 'Column87',
 'Column88',
 'Column89',
 'Column90',
 'Column91',
 'Column92',
 'Column93',
 'Column94',
 'Column95',
 'Column96',
 'Column97',
 'Column98',
 'Column99']

In [81]:
df = pd.DataFrame(np.random.randn(number_rows,number_columns),
                  columns = columns_name, index=rows_name)

In [82]:
df.head()

,Column0,Column1,Column2,Column3,Column4,Column5,Column6,Column7,Column8,Column9,...,Column90,Column91,Column92,Column93,Column94,Column95,Column96,Column97,Column98,Column99
Row0,-0.720301,1.718780,1.541226,1.520189,-0.755263,0.187319,-1.274427,0.157501,0.874679,-0.961453,...,-0.797839,-0.228791,0.229018,-1.991802,2.124089,0.484285,-0.306234,1.134837,-0.126511,0.095206
Row1,0.428561,-0.043026,-0.628375,0.408771,-0.686359,-1.963524,-0.272176,0.308592,-2.385503,0.486458,...,-2.635566,-0.264067,-0.317586,-0.294251,-0.622919,0.442259,-1.699743,-2.089982,0.164419,-0.362417
Row2,0.452921,0.190230,1.160037,0.825209,-1.508596,-1.118298,-1.089080,-0.333971,0.795924,-0.414806,...,-0.379843,0.084189,-1.052261,-0.594055,0.375574,-0.239365,0.467681,0.139671,1.985294,0.019749
Row3,0.387837,0.639760,-1.246034,-1.060032,0.163801,-0.240304,-0.603356,0.324023,0.570979,0.667731,...,-1.815369,-0.343143,-1.586591,-2.477481,-2.080796,0.453772,-0.892994,-0.951603,0.324038,-1.761265
Row4,-0.209952,0.755194,-1.748632,1.055620,-0.926628,-1.511346,0.700836,-1.279139,1.674674,1.044165,...,-0.639057,-0.610292,-1.810795,0.899747,1.376729,0.086550,0.645144,-1.252194,-0.397341,-0.227710

In [83]:
df.tail()

,Column0,Column1,Column2,Column3,Column4,Column5,Column6,Column7,Column8,Column9,...,Column90,Column91,Column92,Column93,Column94,Column95,Column96,Column97,Column98,Column99
Row995,1.837329,-1.092476,1.411149,-0.234615,2.249318,0.034854,0.041238,-0.185717,-1.187434,-0.578195,...,-0.631068,-0.042908,-1.239564,-0.324182,-0.365378,0.438019,1.031958,-1.496843,1.229869,1.532056
Row996,-0.277333,0.578628,0.197129,0.209725,0.072923,0.382230,-0.665006,0.066289,-1.134968,-1.157777,...,0.510736,-0.910649,0.934129,0.424365,0.300866,0.717467,1.387971,-0.407871,-0.461895,2.140507
Row997,0.788283,0.018751,-2.991846,1.436655,0.000408,-1.256032,1.758472,0.989220,-0.452843,-0.916590,...,0.566476,1.007146,0.912151,-0.397965,-1.611221,-0.885385,-0.487538,-2.824988,0.331741,1.421283
Row998,0.332334,1.463714,1.391925,0.779379,-0.099446,0.394086,-0.484928,0.625071,-0.124871,0.774067,...,0.797564,-0.866052,0.447644,0.811556,-0.808934,-0.044232,-0.795113,1.805140,0.496130,0.209156
Row999,0.332673,-0.597676,-0.103369,1.316808,-0.685595,0.407240,0.497578,0.965297,-1.011043,-1.139490,...,1.900744,-1.885153,-1.913610,-0.819014,0.033188,0.744954,0.496208,-0.958478,0.305918,0.331399

In [85]:
df ["Column8"].head()

Row0    0.874679
Row1   -2.385503
Row2    0.795924
Row3    0.570979
Row4    1.674674
Name: Column8, dtype: float64

In [86]:
df.Column3

Row0      1.520189
Row1      0.408771
Row2      0.825209
Row3     -1.060032
Row4      1.055620
            ...
Row995   -0.234615
Row996    0.209725
Row997    1.436655
Row998    0.779379
Row999    1.316808
Name: Column3, Length: 1000, dtype: float64

In [87]:
df.loc["Row10"]

Column0    -0.149232
Column1     0.391772
Column2    -1.110892
Column3     0.062454
Column4     1.404216
              ...
Column95    1.466737
Column96   -1.531529
Column97   -0.047499
Column98   -1.147841
Column99    1.614344
Name: Row10, Length: 100, dtype: float64

In [88]:
df.loc[["Row2","Row90"]]

,Column0,Column1,Column2,Column3,Column4,Column5,Column6,Column7,Column8,Column9,...,Column90,Column91,Column92,Column93,Column94,Column95,Column96,Column97,Column98,Column99
Row2,0.452921,0.190230,1.160037,0.825209,-1.508596,-1.118298,-1.08908,-0.333971,0.795924,-0.414806,...,-0.379843,0.084189,-1.052261,-0.594055,0.375574,-0.239365,0.467681,0.139671,1.985294,0.019749
Row90,-0.492169,-1.379028,-0.266891,-0.775636,0.488853,0.159685,-0.19525,-0.991116,-0.098146,-0.372349,...,0.158205,-1.248617,-0.821803,-1.295901,0.801650,0.109312,0.994591,-1.096519,-2.452026,0.440181

In [89]:
df.iloc[5]

Column0    -2.202885
Column1     0.574283
Column2     0.233322
Column3    -1.775359
Column4    -0.467450
              ...
Column95    0.572629
Column96    1.525935
Column97    1.861773
Column98   -0.648979
Column99   -0.000337
Name: Row5, Length: 100, dtype: float64

In [90]:
Row2, Row4, Row6, Row8, Row10

NameError: name 'Row2' is not defined

In [91]:
df.iloc[0:11:2]

,Column0,Column1,Column2,Column3,Column4,Column5,Column6,Column7,Column8,Column9,...,Column90,Column91,Column92,Column93,Column94,Column95,Column96,Column97,Column98,Column99
Row0,-0.720301,1.718780,1.541226,1.520189,-0.755263,0.187319,-1.274427,0.157501,0.874679,-0.961453,...,-0.797839,-0.228791,0.229018,-1.991802,2.124089,0.484285,-0.306234,1.134837,-0.126511,0.095206
Row2,0.452921,0.190230,1.160037,0.825209,-1.508596,-1.118298,-1.089080,-0.333971,0.795924,-0.414806,...,-0.379843,0.084189,-1.052261,-0.594055,0.375574,-0.239365,0.467681,0.139671,1.985294,0.019749
Row4,-0.209952,0.755194,-1.748632,1.055620,-0.926628,-1.511346,0.700836,-1.279139,1.674674,1.044165,...,-0.639057,-0.610292,-1.810795,0.899747,1.376729,0.086550,0.645144,-1.252194,-0.397341,-0.227710
Row6,0.106970,0.188008,-1.037228,1.656228,-2.092277,-0.482601,1.203803,-1.060840,-1.782492,1.235573,...,0.656047,-0.265867,-0.534087,-0.192465,-0.245253,0.337044,0.742486,-0.557758,0.352591,1.095931
Row8,-0.058191,-1.311021,0.056291,-0.796356,-0.433376,-0.440977,-0.813497,-2.551789,-0.742328,-0.322787,...,-1.562296,0.477436,0.396026,0.725183,0.679777,0.643649,0.844039,-0.309460,-0.692208,1.226387
Row10,-0.149232,0.391772,-1.110892,0.062454,1.404216,1.261989,0.646917,0.426910,0.871348,0.039079,...,-0.666076,0.064100,0.452001,-0.370247,1.332740,1.466737,-1.531529,-0.047499,-1.147841,1.614344